export const PRODUCTS = [
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
    {
      title: "STI Men's Shirts",
      img: "wgxv5_400.webp",
      mrp: 999,
      discountedPrice: 214,
      deliveryType: "Free Delivery",
      rating: 3.9,
      reviews: 13071,
    },
  ];